name = "Rust"
grammar = "rust"
path_suffixes = ["rs"]
line_comments = ["// ", "/// ", "//! "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = false, newline = true },
    { start = "[", end = "]", close = false, newline = true },
    { start = "(", end = ")", close = false, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = ["string", "comment"] },
    { start = "\"", end = "\"", close = false, newline = false, not_in = ["string"] },
    { start = "/*", end = " */", close = false, newline = false, not_in = ["string", "comment"] },
]
collapsed_placeholder = " /* ... */ "
