name = "YAML"
grammar = "yaml"
path_suffixes = ["yml", "yaml"]
line_comments = ["# "]
autoclose_before = ",]}"
brackets = [
    { start = "{", end = "}", close = false, newline = true },
    { start = "[", end = "]", close = false, newline = true },
    { start = "\"", end = "\"", close = false, newline = false, not_in = ["string"] },
]

auto_indent_using_last_non_empty_line = false
increase_indent_pattern = ":\\s*[|>]?\\s*$"
prettier_parser_name = "yaml"
tab_size = 2
