name = "CSS"
grammar = "css"
path_suffixes = ["css"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = false, newline = true },
    { start = "[", end = "]", close = false, newline = true },
    { start = "(", end = ")", close = false, newline = true },
    { start = "\"", end = "\"", close = false, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = false, newline = false, not_in = ["string", "comment"] },
]
word_characters = ["-"]
block_comment = ["/* ", " */"]
prettier_parser_name = "css"
