name = "C++"
grammar = "cpp"
path_suffixes = ["cc", "hh", "cpp", "h", "hpp", "cxx", "hxx", "c++", "ipp", "inl", "cu", "cuh"]
line_comments = ["// "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = false, newline = true },
    { start = "[", end = "]", close = false, newline = true },
    { start = "(", end = ")", close = false, newline = true },
    { start = "\"", end = "\"", close = false, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = false, newline = false, not_in = ["string", "comment"] },
    { start = "/*", end = " */", close = false, newline = false, not_in = ["string", "comment"] },
]
