name = "proto"
grammar = "proto"
path_suffixes = ["proto"]
line_comments = ["// "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = false, newline = true },
    { start = "[", end = "]", close = false, newline = true },
    { start = "(", end = ")", close = false, newline = true },
    { start = "\"", end = "\"", close = false, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = false, newline = false, not_in = ["comment", "string"] },
    { start = "/*", end = " */", close = false, newline = false, not_in = ["comment", "string"] },
]
