name = "JSON"
grammar = "json"
path_suffixes = ["json"]
line_comments = ["// "]
autoclose_before = ",]}"
brackets = [
    { start = "{", end = "}", close = false, newline = true },
    { start = "[", end = "]", close = false, newline = true },
    { start = "\"", end = "\"", close = false, newline = false, not_in = ["string"] },
]
tab_size = 2
prettier_parser_name = "json"
