name = "Regex"
grammar = "regex"
autoclose_before = ")]}"
brackets = [
  { start = "(", end = ")", close = false, newline = false },
  { start = "{", end = "}", close = false, newline = false },
  { start = "[", end = "]", close = false, newline = false },
]
